export const BUSINESS_CATEGORIES = [
    'Agriculture',
    'Automobiles',
    'Banks',
    'Ecommerce',
    'Education',
    'Energy',
    'Fintech',
    'Food & Drink',
    'Health',
    'Hospitality',
    'Insurance',
    'IT Services',
    'Jobs',
    'Legal Services',
    'Logistics',
    'Media',
    'Real Estate',
    'Telecom',
    'Travel & Hotels',
    'Other'
];
